twitter:
  id: 'oddward_io'
  href: 'https://www.twitter.com/'
  title: 'Twitter profile'
  icon: 'fa fa-twitter'
  bg-color: 'bg-[#1da1f2]'

instagram:
  id: 'mugtaba.g'
  href: 'https://instagram.com/'
  title: 'Main Instagram'
  icon: 'fa fa-instagram'
  bg-color: 'bg-insta-onhover'

instagramdev:
  id: 'oddward.io'
  href: 'https://instagram.com/'
  title: 'Dev Instagram'
  icon: 'fa fa-instagram'
  bg-color: 'bg-insta-onhover'

github:
  id: 'Oddward'
  href: 'https://github.com/'
  title: 'GitHub repositories'
  icon: 'fa fa-github'
  bg-color: 'bg-black'

codepen:
  id: 'oddward'
  href: 'https://codepen.io/'
  title: 'CodePen playground'
  icon: 'fa fa-codepen'
  bg-color: 'bg-black'

linkedin:
  id: 'mugtabagaroot'
  href: 'https://linkedin.com/in/'
  title: 'Linkedin Profile'
  icon: 'fa fa-linkedin'
  bg-color: 'bg-[#0077B5]'

dev:
  id: 'oddward'
  href: 'https://dev.to/'
  title: 'Dev profile'
  icon: 'fab fa-dev'
  bg-color: 'bg-black'

dribbble:
  id: 'Oddward'
  href: 'https://dribbble.com/'
  title: 'Dribbble portfolio'
  icon: 'fab fa-dribbble'
  bg-color: 'bg-[#ea4c89]'